### ISSUE TITLE
Module fails to load during protractor tests

### ISSUE THREAD

**Issue by rmoetwil** [ggoodman/angular-drag-drop#1]
While writing protractor e2e tests we noticed that this module fails to load.

```
Failed to instantiate module filearts.dragDrop due to:\nError: [$injector:nomod] Module 'filearts.dragDrop' is not available! You either misspelled the module name or forgot to load it. 
```

If we use the source code (and remove the require() options) the module gets loaded while using protractor testing.

Seems to be related to the Webpack build process thingy.

Do you the reason why, or might have a solution?

Note:
The module itself works when using it in an application through a browser.

**Comment by evaRA** [comment]
We have partially solved the problem by modifying the file src/angular-drag-drop.js and using this single modified file instead of the whole library . This way it works in both our application and protractor tests.
But we would like to use the library again later.

We posted this problem in Stackoverflow. Refer to it for more details:
http://stackoverflow.com/questions/31985285/angularjs-e2e-test-protractor-failed-to-instantiate-module

**Comment by ggoodman** [comment]
@evaRA and @rmoetwil if you happen to still be using this lib, I've just published `v2.0.0` with some (minor, depending on how you are using this library) breaking changes. I'm curious if the adjusted packaging format works for you?

**Comment by ggoodman** [comment]
Closing. Please indicate if this issue is still important to you.

**Comment by evaRA** [comment]
@ggoodman Thank you for the fix. At this moment we are not maintaining the application, but eventually we would like to improve some features (e.g. to drop an element doesn't work so good and it requires to place very accurate the mouse). We will let you know by then.
