### ISSUE TITLE
Providing feature for remembering the order

### ISSUE THREAD

**Issue by shraddha1112** [ggoodman/angular-drag-drop#2]
hello,
I am evaluating an client requirement where in we want the content drag and drop but has to be remembered and need to be reloaded.
I could drag and drop using your plugin. But will it be possible to remember the ordering may be storing css into db or user folder and reloading when user logs in. 
Please help me with feasibility,

Regards,
Shraddha

**Comment by evaRA** [comment]
Hello,

I think the feature you want to implement is not related to the drag-and-drop library, but with a storage mechanism of the object you want to remember (drop container in this case). 

In my application, I just use that library to make a custom drag and drop in AngularJS, since the default library provided by the platform is available for lists, and I am using a table. In order to "remember" the changes made in the drag container, I have to save the object in DB (I use nodeJS for this). 

Regards,
Eva

**Comment by evaRA** [comment]
*Sorry, changes made in the DROP container.

**Comment by ggoodman** [comment]
As suggested by @evaRA, this module does not do ordering for you. That is something you could implement on top of this, in which case you could also persist and reload the order from whatever storage you want.
